### ISSUE TITLE
DataObjects::URI.new with arguments is deprecated warning

### ISSUE THREAD

**Issue by emonti** [datamapper/dm-do-adapter#4]
As of data_objects 0.10.5 I have begun getting the following warning in my datamapper project

DataObjects::URI.new with arguments is deprecated, use a Hash of URI components (.../gems/dm-do-adapter-1.1.0/lib/dm-do-adapter/adapter.rb:231:in `new')

**Comment by emonti** [comment]
sorry, i just checked. looks like you've already fixed this in 1.1.1 - push that gem! :)

**Comment by solnic** [comment]
@emonti yeah man we'll be releasing within the next few days...we just need to find some time to write release notes :)

**Comment by DAddYE** [comment]
@solnic the released gem don't contain this fix... why?

**Comment by solnic** [comment]
@DAddYE we're waiting with releasing dm 1.1.1 because we found a nasty bug in latest DO. Unfortunately we already bumped DO dependency to 0.10.5 that's why it's a blocker :(

**Comment by dgmdan** [comment]
Ran into this issue as well when using the current released gem (1.1.0).  Glad to know an update is on the way.

**Comment by bgreenlee** [comment]
Any update on when the 1.1.1 gem will be pushed?

**Comment by solnic** [comment]
@bgreenlee Next week and probably it's gonna be 1.2.0

**Comment by chenillen** [comment]
didn't find the 1.1.1 gem update....

**Comment by orlybg** [comment]
any workaround while the new gem is pushed?

**Comment by jasonmadigan** [comment]
Glad to hear a fix is coming.

**Comment by delonnewman** [comment]
Glad to hear a fix is coming too, but I'd like to second @orlybg.

**Comment by solnic** [comment]
@delonnewman yeah just apply this patch https://github.com/datamapper/dm-do-adapter/commit/7f0b53d1ada8735910e04ff37d60c6ff037ce288

**Comment by delonnewman** [comment]
thanks @solnic

**Comment by whoshallsucceed** [comment]
Noob question: How apply this patch ? I use DataMapper in a Sinatra app. I will not patch the gem itself. So?

**Comment by solnic** [comment]
@whoshallsucceed just use latest RC2 of DataMapper, it's fixed there `gem install datamapper --pre`

**Comment by whoshallsucceed** [comment]
Oh thanks!

**Comment by jinzishuai** [comment]
somehow I am unable to install data_mapper, even though the dm-core-1.2.0.rc2 was just installed:

```
# gem install dm-core dm-aggregates data_mapper --pre
Successfully installed dm-core-1.2.0.rc2
Successfully installed dm-aggregates-1.2.0.rc2
ERROR:  Error installing data_mapper:
    data_mapper requires dm-aggregates (= 1.2.0.rc2, runtime)
2 gems installed
Installing ri documentation for dm-core-1.2.0.rc2...
Installing ri documentation for dm-aggregates-1.2.0.rc2...
Installing RDoc documentation for dm-core-1.2.0.rc2...
Installing RDoc documentation for dm-aggregates-1.2.0.rc2...
```

**Comment by solnic** [comment]
@jinzishuai weird, works for me:

```
gem install dm-core dm-aggregates data_mapper --pre

Fetching: dm-core-1.2.0.rc2.gem (100%)
Successfully installed dm-core-1.2.0.rc2
Fetching: dm-aggregates-1.2.0.rc2.gem (100%)
Successfully installed dm-aggregates-1.2.0.rc2
Fetching: dm-constraints-1.2.0.rc2.gem (100%)
Fetching: dm-migrations-1.2.0.rc2.gem (100%)
Fetching: dm-transactions-1.2.0.rc2.gem (100%)
Fetching: dm-serializer-1.2.0.rc2.gem (100%)
Fetching: dm-timestamps-1.2.0.rc2.gem (100%)
Fetching: dm-validations-1.2.0.rc2.gem (100%)
Fetching: bcrypt-ruby-3.0.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: stringex-1.3.0.gem (100%)
Fetching: dm-types-1.2.0.rc2.gem (100%)
Fetching: data_mapper-1.2.0.rc2.gem (100%)
Successfully installed dm-constraints-1.2.0.rc2
Successfully installed dm-migrations-1.2.0.rc2
Successfully installed dm-transactions-1.2.0.rc2
Successfully installed dm-serializer-1.2.0.rc2
Successfully installed dm-timestamps-1.2.0.rc2
Successfully installed dm-validations-1.2.0.rc2
Successfully installed bcrypt-ruby-3.0.1
Successfully installed stringex-1.3.0
Successfully installed dm-types-1.2.0.rc2
Successfully installed data_mapper-1.2.0.rc2
12 gems installed
```

**Comment by jinzishuai** [comment]
Hi Piotr,

I am running RHEL-6.1. What are you running?
Thanks.

Shi
On Fri, Sep 23, 2011 at 1:08 PM, Piotr Solnica <
reply@reply.github.com>wrote:

> @jinzishuai weird, works for me:
> 
> ```
> gem install dm-core dm-aggregates data_mapper --pre
> 
> Fetching: dm-core-1.2.0.rc2.gem (100%)
> Successfully installed dm-core-1.2.0.rc2
> Fetching: dm-aggregates-1.2.0.rc2.gem (100%)
> Successfully installed dm-aggregates-1.2.0.rc2
> Fetching: dm-constraints-1.2.0.rc2.gem (100%)
> Fetching: dm-migrations-1.2.0.rc2.gem (100%)
> Fetching: dm-transactions-1.2.0.rc2.gem (100%)
> Fetching: dm-serializer-1.2.0.rc2.gem (100%)
> Fetching: dm-timestamps-1.2.0.rc2.gem (100%)
> Fetching: dm-validations-1.2.0.rc2.gem (100%)
> Fetching: bcrypt-ruby-3.0.1.gem (100%)
> Building native extensions.  This could take a while...
> Fetching: stringex-1.3.0.gem (100%)
> Fetching: dm-types-1.2.0.rc2.gem (100%)
> Fetching: data_mapper-1.2.0.rc2.gem (100%)
> Successfully installed dm-constraints-1.2.0.rc2
> Successfully installed dm-migrations-1.2.0.rc2
> Successfully installed dm-transactions-1.2.0.rc2
> Successfully installed dm-serializer-1.2.0.rc2
> Successfully installed dm-timestamps-1.2.0.rc2
> Successfully installed dm-validations-1.2.0.rc2
> Successfully installed bcrypt-ruby-3.0.1
> Successfully installed stringex-1.3.0
> Successfully installed dm-types-1.2.0.rc2
> Successfully installed data_mapper-1.2.0.rc2
> 12 gems installed
> ```
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/datamapper/dm-do-adapter/issues/4#issuecomment-2181791

## 

Shi Jin, Ph.D.

**Comment by solnic** [comment]
@jinzishuai osx lion but this shouldn't matter

**Comment by kagminjeong** [comment]
This caused https://github.com/integrity/integrity/commit/9b990ab0588de0482e00e65895c20fed3df41002 and subsequently https://github.com/integrity/integrity/pull/143#issuecomment-3225064. Why could you not have left the old API alone?
